Feature/get api comments
cojar/whats_hot_backend pull request #11
Opened 2023-12-20 14:58 UTC by kael0595

## 미리보기(사진 or GIF)
<img src="" width="500px">
성공 예시
<img width="1492" alt="스크린샷 2023-12-20 오후 11 53 39" src="https://github.com/cojar/whats_hot_backend/assets/125107973/ef6eeddd-7e3b-47d7-aaff-19b27dc24346">

<img width="1491" alt="스크린샷 2023-12-20 오후 11 54 24" src="https://github.com/cojar/whats_hot_backend/assets/125107973/3186e996-ff6b-4e5e-a43c-10fd087ec2e3">

실패 예시
<img width="1485" alt="스크린샷 2023-12-20 오후 11 53 58" src="https://github.com/cojar/whats_hot_backend/assets/125107973/208d2bd2-3dfa-4f60-8833-b0ca6089e08e">

<img width="1492" alt="스크린샷 2023-12-20 오후 11 55 08" src="https://github.com/cojar/whats_hot_backend/assets/125107973/04ff796c-50ca-4b6b-a105-9217f95429d4">

## 작업 브랜치
- feature/get-api-comments

## 작업 진행 및 변경 사항
- S-04-02 TC 작성
- F-04-02-01 TC 작성
- get comments/me 작성
- S-04-03 TC 작성
- F-04-03-01 TC 작성

## 이후 할 작업
- api/comments 잔여 작업

## P.S.
##### 확인 후 리뷰 부탁합니다.

2023-12-20 17:59 UTC, pintordev requested changes
수정 사항 반영해주세요

2023-12-20 17:59 UTC, pintordev commented on src/main/java/com/cojar/whats_hot_backend/domain/comment_module/comment/repository/CommentRepository.java
findAllByAuthor 가 좀 더 부합할 것 같아요

2023-12-20 17:59 UTC, pintordev commented on src/main/java/com/cojar/whats_hot_backend/domain/comment_module/comment/controller/CommentController.java
validate 이름은 컨트롤러 이름을 접두사로 하는 게 좋을 것 같고,
매개변수에 author 넣어서 내부 서비스 로직에서 처리하는 게 좋겠습니다.
ex.) if (this.commentRepository.countByAuthor(Member author) == 0)
List<CommentDto> 형태로 넘기게 되면 각 댓글에 self 링크가 달리지 않아 다른 방식으로 넘겨줘야 할 것 같습니다

2023-12-20 17:59 UTC, pintordev commented on src/main/java/com/cojar/whats_hot_backend/domain/comment_module/comment/service/CommentService.java
여기도 리포지터리 메서드를 이용하는 방식으로 했으면 좋겠습니다
ex.) existById(comment.id);

2023-12-20 17:59 UTC, pintordev commented on src/main/java/com/cojar/whats_hot_backend/domain/comment_module/comment/controller/CommentController.java
엔드 포인트 2개를 한번에 작업하신 것 같습니다
따로 분할해서 pr 올려주세요

2023-12-20 17:59 UTC, pintordev commented on src/test/java/com/cojar/whats_hot_backend/domain/comment_module/comment/controller/CommentControllerTest.java
이 부분도 분할해서 올려주세요

2023-12-21 04:24 UTC, ohgil reviewed
확인했습니다

2023-12-21 07:28 UTC, tjqls reviewed
확인했습니다

2023-12-21 09:38 UTC, pintordev reviewed
전부 확인했습니다
머지해주세요

2023-12-21 09:40 UTC, merged